# Generated by Django 2.2 on 2025-11-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefeeditem',
            name='moretext',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
